### ISSUE TITLE
Questions about preprocessed data results

### ISSUE THREAD

**Issue by MY-Park** [jiepengwang/NeuRIS#11]
Hi, thank you for your awesome work, but I have a question about the quality of the preprocessed data results.

1. 
![image](https://user-images.githubusercontent.com/33853683/192227008-d7ac76f5-4778-419a-91e5-8c25c24704e1.png)
Above is the result of ScanNet 0050 scene from the data you shared.

2. 
![image](https://user-images.githubusercontent.com/33853683/192225052-a9fe0bd3-16ac-4f91-9f6d-0777d67db118.png)
![image](https://user-images.githubusercontent.com/33853683/192225155-37ff99a3-9973-4185-bd3d-34c4a977e3dd.png)
Above is the result of the same scene with the preprocessing pipeline you provided, while only using the images. To be clear, from only images -> exp_preprocess.py -> get data -> training. 
However, there's so much gap between the results, so I have 2 questions.

1. To get the quality of the first mesh, should we use the ground truth depth? 
2. Could you give me some advice to get better result on the second pipeline? I want to get better result on custom data. 

Thanks a lot!

**Comment by jiepengwang** [comment]
GT depth requires a depth sensor. Maybe you can try to integrate the sparse depth from SfM or the dense depth from openMVS. This should help to improve the quality and only rely on the RGB information. For your experiment on the ScanNet, I'm not sure what happened. Maybe you can check whether the calibrated camera poses are correct or there are sufficient images covering the whole room and objects in the room.

**Comment by MY-Park** [comment]
I see, thanks for your comment. As you mentioned, I think the problem was related to insufficient point cloud extracted from openMVS. When I retried with more featureful scene the result got much better. I will close the issue. Thank you!
