### ISSUE TITLE
Problem about making private data: No such file or directory: 'NeuRIS/openMVS_build/bin/ExportData'

### ISSUE THREAD

**Issue by SimonCK666** [jiepengwang/NeuRIS#16]
When I made my own data, I met one folder called '/openMVS_build/bin/ExportData' which did not exist.

<img width="1170" alt="Screen Shot 2022-10-17 at 15 55 24" src="https://user-images.githubusercontent.com/57851315/196120744-dc35c60a-011b-407d-8704-345b21d59c37.png">

**Comment by jiepengwang** [comment]
Hi, you need to compile openMVS to get 'ExportData'. Please use the provided openMVS zip to do the compilation instead of the official openMVS repo.

**Comment by murphyl4** [comment]
Thanks

**Comment by SimonCK666** [comment]
@jiepengwang Thank you very much!
