### ISSUE TITLE
About the pretrained normal estimation model

### ISSUE THREAD

**Issue by lzhnb** [jiepengwang/NeuRIS#2]
Thanks for your excellent work.

I'm glad that the `Add data preprocessing code` is in your TODO.
In our acknowledge, the ScanNet dataset in this project is based on the NerfingMVS's. A straightforward way is to release the pretrained model of the [normal estimate model](https://github.com/MARSLab-UMN/TiltedImageSurfaceNormal) so that we can estimate the normal by ourselves.

For training the normal estimate model in ScanNet, TiltedImageSurfaceNormal divided the ScanNet dataset into training split with 199720 images and testing split with 64319 images. As you said in the paper, you divided the it into training split with 1180 scenes and testing split with 433 scenes. Are the divisions the same? If not, please provide the relevant data.

Thanks! :)

**Comment by jiepengwang** [comment]
Thanks for your suggestion. We will release the pretrained model.  And for the training/testing splits we used, they are different from TiltedSN. The code related to the preprocessing code of getting the splits will also be released, where more details can be found.

Best wishes,
Jiepeng
