### ISSUE TITLE
Special settings about the rendered scene

### ISSUE THREAD

**Issue by LLLYLong** [jiepengwang/NeuRIS#28]
Thanks for your nice work and released code! @jiepengwang 
Reading through the papers and experiments, I have a question, is there any special setup done to the scene rendered from the correspondence data that allows the rendered scene to be a cube, and how well it overcomes the shape-radiance ambiguity

**Comment by jiepengwang** [comment]
Thanks for your interest in our work.  Initially, we normalize the scenes and camera poses into a unit cube by utilizing the scanned point cloud data. Then, we employ these normalized camera poses to train our models.

**Comment by LLLYLong** [comment]
> Thanks for your interest in our work. Initially, we normalize the scenes and camera poses into a unit cube by utilizing the scanned point cloud data. Then, we employ these normalized camera poses to train our models.

Thank you very much for your reply, I'll go through the code again.
