### ISSUE TITLE
How can I do inferencing with my own images ?

### ISSUE THREAD

**Issue by holmes27** [jiepengwang/NeuRIS#29]
What are things I need to keep in my mind for the image (properties) and how do I preprocess it?

**Comment by jiepengwang** [comment]
Thanks for your interest in our work. You can follow the the pipeline here (https://github.com/jiepengwang/NeuRIS/tree/main/preprocess) and (https://github.com/jiepengwang/NeuRIS/blob/5168dcc092e580892e943cc1da29d36b7a7fbf61/preprocess/sfm_mvs.py#L230) to prepare your custom data for training and inference.
