### ISSUE TITLE
Missing of function

### ISSUE THREAD

**Issue by Baobaohzj** [jiepengwang/NeuRIS#3]
Thanks for your excellent work!!!

In this repo, I can't find the implantation function of [`write_list_to_txt`](https://github.com/jiepengwang/NeuRIS/blob/c07a3bd780fcb0b60f5e093d5a5ba4206f8a2fca/preprocess/sfm_mvs.py#L102).

**Comment by jiepengwang** [comment]
Sorry, the implementation is added. Please try again. Thanks.
