### ISSUE TITLE
make dataset

### ISSUE THREAD

**Issue by WyouyouX** [jiepengwang/NeuRIS#30]
Hello!   What do I need to provide in addition to the images to run the exp_preprocess.py?  Do I need to place depth maps, camera positions, etc. in folders?   Because when I run exp_preprocess.py I always report an error that the file doesn't exist.   I read the instructions you gave our for making the dataset, and it seems that I only need to provide images?
If additional information is needed, could you give me some advice on how to get it?  I'm new to this field and I'm not familiar with it.  Thank you very much!

**Comment by jiepengwang** [comment]
Thanks for your interest in our work. We provide the scripts to prepare training data from ScanNet data and custom data. Please refer to the instructions here (https://github.com/jiepengwang/NeuRIS/tree/main/preprocess) and the corresponding code for more details.
