### ISSUE TITLE
Got empty mesh after discarding normal prior

### ISSUE THREAD

**Issue by BianFeiHu** [jiepengwang/NeuRIS#5]
Hi, thanks for your impressive work, i want to compare result with NeuS, so i set normal_weight = 0.0 in config file. But after training i can't get valid mesh with marching cube. But the result with normal prior is good. Could you give me some advice?

**Comment by AlbertHuyb** [comment]
Hello @BianFeiHu, 

Have you got correct results on ScanNet? 

Could you please provide some experience running on ScanNet? 

I show the problem I met in another thread [here](https://github.com/jiepengwang/NeuRIS/issues/8).

Thanks!
