### ISSUE TITLE
The depth of the openMVG/openMVS output is incorrect

### ISSUE THREAD

**Issue by LiXinghui-666** [jiepengwang/NeuRIS#6]
Thank you for your excellent work. However, during the preprocessing of my own data, a shape error occurs in 
```python
depth0 = np.load(path_depth0).reshape(size_image[1], size_image[0])
```
The shape of path_depth0 is 518400(540*960), but the shape of size_image is (1080*1920)，How can I fix this part of the error?

**Comment by jiepengwang** [comment]
Hi, do you change the value of original_size_img and cropped_size_img according to your own data? (https://github.com/jiepengwang/NeuRIS/blob/7c085b2bd293e61ef7f8655fa1f13e733bbd5ba8/exp_preprocess.py#L53)

**Comment by LiXinghui-666** [comment]
> 

Yes， I'm sure to change the value of original_size_img and cropped_size_img according to my own data.The output results of ply, cropping images, and pose are correct, but there are errors in the depth, which puzzles me.

**Comment by w080707** [comment]
Hi, is the problem solved now? The width and height in cropped_size_img should satisfy the ratio 4:3. Do you set the value in this way?

**Comment by jiepengwang** [comment]
I'm not sure where is wrong. Does the width and height of cropped_size_img satisfy the ratio  4:3?  A minor suggestion is that maybe you can track the change of depth map size when running the program and find where is wrong.

**Comment by MY-Park** [comment]
Hi, thank you for your excellent work! :)

I also met the same error while preprocessing my own data, and finally got rid of the error after making 
`original_size_img = (960, 720)
cropped_size_img = (960, 720)`

However, still I wondering why only the preprocess works on this size.

**Comment by LiXinghui-666** [comment]
> I'm not sure where is wrong. Does the width and height of cropped_size_img satisfy the ratio 4:3? A minor suggestion is that maybe you can track the change of depth map size when running the program and find where is wrong.

my cropped_size_img is(1360,1020), satifing the ratir 4:3.
```python
original_size_img = (1920, 1080)
cropped_size_img = (1360, 1020) 
```

**Comment by MY-Park** [comment]
I fixed the issue by 
1. making image file indices as the format the author gave. ex) 0000.png, 0001.png, ... 0300.png 
2. fix NeuRIS/preprocess/sfm_mvs.py > def select_depths  
to resize depth.npy from 960 * 720 to 1920 * 1440 (same size with the images)
